# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05b08a99e88acbebcb90a33a69059d21381ea0e269e8e0d80d1b876afc11b489866f4496efe2229689196cf4d524ecec8ad0f511f0aad84fe4035d81d065a49f

test:
  secret_key_base: cee5e983c4f18bd2a9d0504d3658bd13339ea5727ed7561f67a7105f43780e67080ef0db0ee39519193e6488de821a52c681dfe0d476ed1700508bec737d7701

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
